-- Create reference table for PLC error and warning codes
-- Source: Übersicht Fehler & Warnungen CB1 (EN) spreadsheet from machine manufacturer
-- 104 codes total: 91 alarms (A-prefix), 13 warnings (W-prefix)

CREATE TABLE IF NOT EXISTS plc_error_codes (
  code        VARCHAR(10) PRIMARY KEY,
  severity    VARCHAR(10) NOT NULL DEFAULT 'alarm',
  description TEXT NOT NULL,
  cause       TEXT,
  solution    TEXT,
  info        TEXT
);

INSERT INTO plc_error_codes (code, severity, description, cause, solution, info) VALUES
  ('A001', 'alarm', 'Main motor thermal', 'Motor protection switch 00-2Q2 has tripped.', 'Check chain and main motor before resetting the motor protection switch.', NULL),
  ('A002', 'alarm', 'Comm. Profinet to main motor inverter', 'Communication between main motor and PLC lost.', 'No voltage at the frequency converter or bus cable not plugged in correctly.', NULL),
  ('A003', 'alarm', 'Error FU main motor', 'Error on the frequency converter that is not being evaluated.', 'Read error code 00-2U0 on the frequency converter display.', NULL),
  ('A010', 'alarm', 'Emergency stop', 'Emergency stop activated', 'Unlock emergency stop button, reset machine', NULL),
  ('A011', 'alarm', 'Safety door monitoring', 'A safety door has been opened', 'Close all safety doors and reset the machine', NULL),
  ('A012', 'alarm', 'Magazine door open', 'The corresponding safety door has been opened', 'Close the relevant safety door and reset the machine', NULL),
  ('A013', 'alarm', 'Door stick heater open', NULL, NULL, NULL),
  ('A014', 'alarm', 'Door cotton wool feed open', NULL, NULL, NULL),
  ('A015', 'alarm', 'Water pump door open', NULL, NULL, NULL),
  ('A016', 'alarm', 'Dryer door open', NULL, NULL, NULL),
  ('A017', 'alarm', 'Dryer heating rod door open', NULL, NULL, NULL),
  ('A018', 'alarm', 'Comb door open', NULL, NULL, NULL),
  ('A019', 'alarm', 'Safety rocker switch on turntable is activated', NULL, NULL, NULL),
  ('A020', 'alarm', 'Control cabinet door open', NULL, NULL, NULL),
  ('A021', 'alarm', 'Blower door open', NULL, NULL, NULL),
  ('A022', 'alarm', 'Gearbox door open', NULL, NULL, NULL),
  ('A029', 'alarm', 'Encoder error quality assurance (ChZ)', E'Incorrectly connected\nBelt broken\nMechanical seat loose', E'Connect encoder according to diagram\nReplace belt\nTighten encoder mechanically', NULL),
  ('A030', 'alarm', 'Encoder error quality assurance (ChA)', 'See A029', 'See A029', NULL),
  ('A031', 'alarm', 'Encoder error quality assurance (ChB)', NULL, NULL, NULL),
  ('A032', 'alarm', 'Encoder error cam unit (ChA)', NULL, NULL, NULL),
  ('A033', 'alarm', 'Encoder error cam unit (ChB)', NULL, NULL, NULL),
  ('A034', 'alarm', 'Encoder error, cam unit (ChZ)', NULL, NULL, NULL),
  ('A035', 'alarm', 'Chain tension max', 'Chain tensioner fully extended', 'Replace chain', NULL),
  ('A040', 'alarm', 'No compressed air', E'Emergency stop activated\nA safety door has been opened\nInsufficient/no pressure at the main valve', E'See A10\nSee A11\nCheck the pressure at the main line, open the throttle valve', E'Reset must be performed twice.\nFirst reset for safety circuit\nSecond reset releases the compressed air'),
  ('A041', 'alarm', 'Belt max. tension', 'Belt tension cylinder fully extended', 'Rebalance dryer', NULL),
  ('A073', 'alarm', 'No rods on chain', E'Chaos in the magazine\nEmpty lever on the magazine flipped\nBrush too close to the magazine wheel\nMilling on magazine wheel too small', E'Align the sticks in the magazine\nFlip lever to release stick feed\nIncrease the distance between the brush and the magazine wheel\nFile milled grooves to make them larger', NULL),
  ('A074', 'alarm', 'Rod magazine empty', 'Level rod in magazine too low', 'Refill magazine', NULL),
  ('A075', 'alarm', 'Slider rod magazine not inserted during dryer heating', 'Empty lever on magazine flipped', 'Flip lever to stop stick feed', NULL),
  ('A076', 'alarm', 'Slider rod magazine not inserted during emptying', NULL, NULL, NULL),
  ('A101', 'alarm', 'Failure of temperature measurement for rod heating, outside top', 'Electrical defect', E'Check cable\nCheck the electrical system', NULL),
  ('A102', 'alarm', 'Failure of temperature measurement for rod heater, outside bottom', NULL, NULL, NULL),
  ('A103', 'alarm', 'Failure of temperature measurement for stick heater inside top', NULL, NULL, NULL),
  ('A104', 'alarm', 'Failure of temperature measurement for rod heater inside bottom', NULL, NULL, NULL),
  ('A109', 'alarm', 'Max. temperature of rod heater inside top', 'Max. temperature of rod heater exceeded', 'Check controller settings', NULL),
  ('A110', 'alarm', 'Max. temperature of rod heater inside bottom', NULL, NULL, NULL),
  ('A113', 'alarm', 'Heating does not close', E'Compressed air valve incorrectly connected\nHeating jaws blocked', E'Check compressed air valve\nClean heating jaws', NULL),
  ('A114', 'alarm', 'Heating closed (at start MC)', '<=', 'Open heater using button', NULL),
  ('A118', 'alarm', 'Thermo glue motor', E'Circuit breaker =04-1Q0 triggered\nMotor defective', E'Switch circuit breaker =04-1Q0 on\nCircuit breaker =04-1Q0 set current limit to 5.0A\nReplace motor', NULL),
  ('A120', 'alarm', 'Hot melt not ready', 'Errors A121, A122, A123, A124, A127', 'Fix all hot melt errors', NULL),
  ('A121', 'alarm', 'Hot melt error', NULL, NULL, NULL),
  ('A122', 'alarm', 'Hot melt valve open (at start MC)', NULL, NULL, NULL),
  ('A123', 'alarm', 'Hot melt pump not activated', 'Compressed air valve on hot melt closed', 'Open the compressed air valve on the hot melt', NULL),
  ('A124', 'alarm', 'Hot melt low temperature', 'Hot melt has not reached operating temperature', 'Wait until hot melt is hot enough', NULL),
  ('A125', 'alarm', 'Glue wheel is down (at start MC)', '<=', 'Move the glue wheel up using the button', NULL),
  ('A126', 'alarm', 'Glue wheel is up (during idle run at start MC)', '<=', 'Lower the glue wheel using the button', NULL),
  ('A127', 'alarm', 'No connection to hot melt device', E'Hot melt is switched off\nConnection to hot melt interrupted\nHot melt has no power supply', E'Switch on the hot melt (switch, front right bottom)\nCheck the LAN cable:\n- at the switch in the control cabinet\n- Interface at the bottom, in the control cabinet\n- Interface at the bottom, outside the control cabinet\n- Hot melt connector in front of the magazine', NULL),
  ('A171', 'alarm', 'Thermo suction dosing device', E'Circuit breaker =05-2Q0 triggered\nMotor defective', E'Switch on circuit breaker =05-2Q0\nSet circuit breaker =05-2Q0 current limit to 5.0A\nReplace motor', NULL),
  ('A172', 'alarm', 'Internal wadding tear', E'Cotton wool torn off\nCotton wool not fed through noise sensor\nInsufficient friction on noise sensor\nNoise sensor sensitivity too low', E'Reinsert cotton wool\nPass cotton wool over noise sensor\nAdjust the position of the noise sensor forward\nIncrease sensitivity using a screwdriver', NULL),
  ('A173', 'alarm', 'Cotton tear outside', 'See A172', NULL, NULL),
  ('A174', 'alarm', 'Cotton wool dosing not at top (at start MC, when cotton wool feed is off)', 'Wadding dispenser at the bottom', 'Start up the wadding dispenser using the button', NULL),
  ('A176', 'alarm', 'Cotton wool is finished (track 1)', 'Cotton wool on lane 1 empty', 'Refill cotton wool', NULL),
  ('A177', 'alarm', 'Cotton wool finished (track 2)', 'Cotton wool on lane 2 empty', NULL, NULL),
  ('A179', 'alarm', 'Metering device not at bottom (at start MC)', 'Dossier device is at the top of the MC at start-up', 'Lower the dosing device using the button', NULL),
  ('A180', 'alarm', 'End position of dosing device', 'Dossier machine has not reached end position', E'Align sensor\nReplace compressed air hoses', NULL),
  ('A185', 'alarm', 'Roll form holder not down (at start MC)', 'Roll form holder cylinder not extended', 'Lower roll form holder using button', NULL),
  ('A190', 'alarm', 'Too many sticks ejected', E'Too many rods identified as defective by QA in a short period of time:\n- Head shape unsuitable (too small/too large)\n- Wrong job selected\n- Contamination at the end of the shaper bar\n- Contamination on the camera lens\n- Incorrect trigger timing\n- Water tear', E'Adjust roll form\nSelect correct job in QA\nClean shaper bar\nClean camera lens\nSet trigger time\nSee A172, then reset', NULL),
  ('A221', 'alarm', 'Thermo fan drying system', 'Circuit breaker =07-2Q2 triggered', E'Switch on circuit breaker =07-2Q2\nSet circuit breaker =07-2Q2 current limit to 4.4A', NULL),
  ('A222', 'alarm', 'Thermo heating drying system', 'Circuit breaker =07-1Q1.1 triggered', E'Switch on circuit breaker =07-1Q1.1\nSet circuit breaker =07-1Q1.1 current limit to 18.5A', NULL),
  ('A223', 'alarm', 'Thermo suction drying system', 'Circuit breaker =07-3Q2 triggered', E'Switch on circuit breaker =07-3Q2\nCircuit breaker =07-3Q2 set current limit to 4.4A', NULL),
  ('A226', 'alarm', 'Comm. Profinet to FU drying unit fan', 'New frequency converter installed', E'Acknowledge error on frequency converter\nRestart machine', NULL),
  ('A227', 'alarm', 'Comm. Profinet to FU drying unit suction unit', NULL, NULL, NULL),
  ('A228', 'alarm', 'Error FU drying unit fan', NULL, NULL, NULL),
  ('A229', 'alarm', 'Error FU drying unit suction unit', NULL, NULL, NULL),
  ('A230', 'alarm', 'Error dryer not ready (at MC start)', NULL, NULL, NULL),
  ('A233', 'alarm', 'Control restart required (switch off and on)', E'Option added in configuration\nOption deselected in configuration', 'Main switch: Off -> On', NULL),
  ('A236', 'alarm', 'Max. temperature drying system', 'Max. temp. exceeded -> Jumo has triggered', E'Switch on ventilation drying system\nSet fans in drying system to run faster\nLower the target temperature\nPerform a mechanical reset on the Jumo', NULL),
  ('A239', 'alarm', 'Dryer thermo fan', 'Circuit breaker =07-2Q2 triggered', E'Switch on circuit breaker =07-2Q2\nCircuit breaker =07-2Q2 current limiter to 4.4A', NULL),
  ('A243', 'alarm', 'Dryer not switched on at machine start', '<=', 'Start dryer', NULL),
  ('A244', 'alarm', 'Spring tension too low', E'Jam in dryer\nBelt tension too low\nSpring broken', E'Remove jam, rebalance dryer\nTighten the belt tensioner\nReplace broken spring', NULL),
  ('A245', 'alarm', 'Spring tension too high', E'Jam in the dryer\nBelt tension too high\nSpring tension too high', E'Remove jam, rebalance dryer\nLoosen belt tensioner\nLoosen spring tension', NULL),
  ('A246', 'alarm', 'Dryer outlet temperature outside range', 'Temperature is not within the range', NULL, NULL),
  ('A271', 'alarm', 'Thermo vacuum motor comb', 'Circuit breaker =08-1Q0 triggered', E'Switch on circuit breaker =08-1Q0\nCircuit breaker =08-1Q0 set current limit to 2.5A', NULL),
  ('A274', 'alarm', 'Too many missing sticks on comb', E'Could not pick up enough sticks with comb:\n- Crossed sticks\n- Bent sticks\n- Too many sticks ejected by QS', E'Check all transfers (magazine, waterfall)\nCheck all guides (no jamming)\nReduce QS settings "Max. bad rods in 5s" value', NULL),
  ('A275', 'alarm', 'Too many missing rods in box 1', E'Too many individual sticks ejected\nPick-up error\nLimit for "Max. missing sticks per pack alarm" set too low', E'Adjust magazine including transfer, roll form, waterfall\nAdjust pick-up\nIncrease limit for "Max. missing sticks per package alarm"', NULL),
  ('A276', 'alarm', 'Too many missing rods in box 2', NULL, NULL, NULL),
  ('A278', 'alarm', 'Scraper end position error', E'Sensor not positioned correctly\nScraper manually moved down', E'Correct sensor position\nMove scraper up using button', NULL),
  ('A280', 'alarm', 'Scraper not at top (at start MC)', NULL, NULL, NULL),
  ('A281', 'alarm', 'Comb not at top (at start MC)', E'Sensor not positioned correctly\nScraper manually moved down', E'Correct sensor position\nMove scraper up using button', NULL),
  ('A282', 'alarm', 'Comb at bottom in rod counter position', NULL, NULL, NULL),
  ('A321', 'alarm', 'Thermo rotary table', 'Circuit breaker =09-1Q2 triggered', E'Switch on circuit breaker =09-1Q2\nSet circuit breaker =09-1Q2 current limit to 3.0A', NULL),
  ('A322', 'alarm', 'Error FU rotary table', 'New frequency converter installed', E'Acknowledge error on frequency converter\nRestart machine', NULL),
  ('A323', 'alarm', 'Error rotary table (FU or sensor)', NULL, NULL, NULL),
  ('A324', 'alarm', 'Rotary table not in position', NULL, NULL, NULL),
  ('A327', 'alarm', 'Packaging not ready', 'Error on the packaging system', 'See error packaging system', NULL),
  ('A328', 'alarm', 'Packaging timeout', NULL, NULL, NULL),
  ('A329', 'alarm', 'No release of rotary table from packaging', 'Approval from the packaging system not received or received too late', NULL, NULL),
  ('A331', 'alarm', 'No release scraper from BV-2A (timeout)', NULL, NULL, NULL),
  ('A332', 'alarm', 'No release scraper from BL12 (timeout)', NULL, NULL, NULL),
  ('A340', 'alarm', 'Packaging connector not plugged in', '<=', E'Connect plug X10 from packaging system\nInsert jumper plug on X10', NULL),
  ('A480', 'alarm', 'Belt tension too high (technician reset)', E'Sensor at top of belt tension cylinder triggered\nSee A245', E'First resolve A245\nThen perform technician reset', NULL),
  ('A481', 'alarm', 'Belt tension too low (technician reset)', E'Sensor at bottom of belt tension cylinder triggered\nSee A244', E'First resolve A244\nThen perform a technician reset', NULL),
  ('W001', 'warning', 'External magazine empty', 'No sticks in outer magazine', 'Refill sticks', NULL),
  ('W002', 'warning', 'Internal magazine empty', 'No sticks in the inner magazine', 'Refill sticks', NULL),
  ('W010', 'warning', 'Min. temperature of external upper rod heater', 'Temperature not yet reached on the outside top', 'Allow to heat up', NULL),
  ('W011', 'warning', 'Min. temperature of rod heater, outside bottom', 'Temperature not yet reached outside bottom', NULL, NULL),
  ('W012', 'warning', 'Min. temperature of rod heater inside top', 'Temperature not yet reached inside top', NULL, NULL),
  ('W013', 'warning', 'Min. temperature of internal bottom rod heater', 'Temperature not yet reached inside bottom', NULL, NULL),
  ('W014', 'warning', 'Chain tension high', 'Chain tightly tensioned', 'Must be changed soon', NULL),
  ('W015', 'warning', 'Wattage usage even though dosing device is up', '<=', 'Move the dosing device down using the button', NULL),
  ('W020', 'warning', 'Min. temperature drying system not reached', 'Temperature not yet reached', 'Allow to heat up', NULL),
  ('W021', 'warning', 'Conditions for drying system not met', NULL, NULL, NULL),
  ('W022', 'warning', 'Close drying system flap', NULL, NULL, NULL),
  ('W023', 'warning', 'Adjust drying system flap', NULL, NULL, NULL),
  ('W040', 'warning', 'Scraper or rotary table too slow', NULL, NULL, NULL)
ON CONFLICT (code) DO UPDATE SET
  severity    = EXCLUDED.severity,
  description = EXCLUDED.description,
  cause       = EXCLUDED.cause,
  solution    = EXCLUDED.solution,
  info        = EXCLUDED.info;
