-- Split the legacy "solution" / "info" columns into two semantically distinct
-- guidance tracks coming from the updated manufacturer error-code sheet:
--   * operator_guidance          (what the operator can attempt themselves)
--   * technical_support_guidance (escalation steps for tech personnel)
--
-- Codes are unchanged; only descriptions, causes, and guidance bodies are
-- refreshed against the latest spreadsheet.

ALTER TABLE plc_error_codes RENAME COLUMN solution TO operator_guidance;
ALTER TABLE plc_error_codes RENAME COLUMN info     TO technical_support_guidance;

INSERT INTO plc_error_codes (code, severity, description, cause, operator_guidance, technical_support_guidance) VALUES
  ('A001', 'alarm', 'Main motor thermal', 'Motor protection switch 00-2Q2 has tripped.', 'Check chain and main motor before resetting the motor protection switch.', NULL),
  ('A002', 'alarm', 'Comm. Profinet to main motor inverter', 'Communication between main motor and PLC lost.', 'No voltage at the frequency converter or bus cable not plugged in correctly.', NULL),
  ('A003', 'alarm', 'Error FU main motor', 'Error on the frequency converter that is not being evaluated.', 'Read error code 00-2U0 on the frequency converter display.', NULL),
  ('A010', 'alarm', 'Emergency stop', 'Emergency stop activated', 'Unlock emergency stop button, reset machine', NULL),
  ('A011', 'alarm', 'Safety door monitoring', 'A safety door has been opened', 'Close all safety doors and reset the machine', NULL),
  ('A012', 'alarm', 'Magazine door open', 'The corresponding safety door has been opened', 'Close the relevant safety door and reset the machine', NULL),
  ('A013', 'alarm', 'Door stick heater open', 'The corresponding safety door has been opened', 'Close the relevant safety door and reset the machine', NULL),
  ('A014', 'alarm', 'Door cotton wool feed open', 'The corresponding safety door has been opened', 'Close the relevant safety door and reset the machine', NULL),
  ('A015', 'alarm', 'Water pump door open', 'The corresponding safety door has been opened', 'Close the relevant safety door and reset the machine', NULL),
  ('A016', 'alarm', 'Dryer door open', 'The corresponding safety door has been opened', 'Close the relevant safety door and reset the machine', NULL),
  ('A017', 'alarm', 'Dryer heating rod door open', 'The corresponding safety door has been opened', 'Close the relevant safety door and reset the machine', NULL),
  ('A018', 'alarm', 'Comb door open', 'The corresponding safety door has been opened', 'Close the relevant safety door and reset the machine', NULL),
  ('A019', 'alarm', 'Safety rocker switch on turntable is activated', 'The corresponding safety door has been opened', 'Close the relevant safety door and reset the machine', NULL),
  ('A020', 'alarm', 'Control cabinet door open', 'The corresponding safety door has been opened', 'Close the relevant safety door and reset the machine', NULL),
  ('A021', 'alarm', 'Blower door open', 'The corresponding safety door has been opened', 'Close the relevant safety door and reset the machine', NULL),
  ('A022', 'alarm', 'Gearbox door open', 'The corresponding safety door has been opened', 'Close the relevant safety door and reset the machine', NULL),
  ('A029', 'alarm', 'Encoder error quality assurance (ChZ)', E'a) Incorrectly connected\nb) Broken belt\nc) Mechanical seat loose', E'a) Connect encoder according to diagram\nb) Replace belt\nc) Tighten encoder mechanically', NULL),
  ('A030', 'alarm', 'Encoder error quality assurance (ChA)', E'a) Incorrectly connected\nb) Broken belt\nc) Mechanical seat loose', E'a) Connect encoder according to diagram\nb) Replace belt\nc) Tighten encoder mechanically', NULL),
  ('A031', 'alarm', 'Encoder error quality assurance (ChB)', E'a) Incorrectly connected\nb) Broken belt\nc) Mechanical seat loose', E'a) Connect encoder according to diagram\nb) Replace belt\nc) Tighten encoder mechanically', NULL),
  ('A032', 'alarm', 'Encoder error cam unit (ChA)', E'a) Incorrectly connected\nb) Broken belt\nc) Mechanical seat loose', E'a) Connect encoder according to diagram\nb) Replace belt\nc) Tighten encoder mechanically', NULL),
  ('A033', 'alarm', 'Encoder error cam unit (ChB)', E'a) Incorrectly connected\nb) Broken belt\nc) Mechanical seat loose', E'a) Connect encoder according to diagram\nb) Replace belt\nc) Tighten encoder mechanically', NULL),
  ('A034', 'alarm', 'Encoder error, cam unit (ChZ)', E'a) Incorrectly connected\nb) Broken belt\nc) Mechanical seat loose', E'a) Connect encoder according to diagram\nb) Replace belt\nc) Tighten encoder mechanically', NULL),
  ('A035', 'alarm', 'Chain tension max', 'Chain tensioner fully extended', 'Replace chain', NULL),
  ('A040', 'alarm', 'No compressed air', E'a) Emergency stop activated\nb) A safety door has been opened\nc) Insufficient/no pressure at the main valve', E'a) Unlock emergency stop button, reset machine\nb) Close all safety doors and reset the machine\nc) Check the pressure at the main line, open the throttle valve', 'Reset must be performed twice. First reset for safety circuit, second reset releases the compressed air'),
  ('A041', 'alarm', 'Belt max. tension', 'Belt tension cylinder fully extended', 'Rebalance dryer', NULL),
  ('A073', 'alarm', 'No rods on chain', E'a) Chaos in the magazine\nb) Empty lever on the magazine flipped\nc) Brush too close to the magazine wheel\nd) Milling on magazine wheel too small', E'a) Align the sticks in the magazine\nb) Flip lever to release stick feed\nc) Increase the distance between the brush and the magazine wheel\nd) File milled grooves to make them larger', NULL),
  ('A074', 'alarm', 'Rod magazine empty', 'Level rod in magazine too low', 'Refill magazine', NULL),
  ('A075', 'alarm', 'Slider rod magazine not inserted during dryer heating', 'Empty lever on magazine flipped', 'Flip lever to stop stick feed', NULL),
  ('A076', 'alarm', 'Slider rod magazine not inserted during emptying', 'Empty lever on magazine flipped', 'Flip lever to stop stick feed', NULL),
  ('A101', 'alarm', 'Failure of temperature measurement for rod heating, outside top', 'Electrical defect', E'1) Check cable\n2) Check the electrical system', NULL),
  ('A102', 'alarm', 'Failure of temperature measurement for rod heater, outside bottom', 'Electrical defect', E'1) Check cable\n2) Check the electrical system', NULL),
  ('A103', 'alarm', 'Failure of temperature measurement for stick heater inside top', 'Electrical defect', E'1) Check cable\n2) Check the electrical system', NULL),
  ('A104', 'alarm', 'Failure of temperature measurement for rod heater inside bottom', 'Electrical defect', E'1) Check cable\n2) Check the electrical system', NULL),
  ('A109', 'alarm', 'Max. temperature of rod heater inside top', 'Max. temperature of rod heater exceeded', 'Check controller settings', NULL),
  ('A110', 'alarm', 'Max. temperature of rod heater inside bottom', 'Max. temperature of rod heater exceeded', 'Check controller settings', NULL),
  ('A113', 'alarm', 'Heating does not close', E'a) Compressed air valve incorrectly connected\nb) Heating jaws blocked', E'a) Check compressed air valve\nb) Clean heating jaws', NULL),
  ('A114', 'alarm', 'Heating closed (at start MC)', '<=', 'Open heater using button', NULL),
  ('A118', 'alarm', 'Thermo glue motor', E'a) Circuit breaker =04-1Q0 triggered\nb) Motor defective', E'a) Switch circuit breaker =04-1Q0 on circuit breaker =04-1Q0 Set current limit to 5.0A\nb) Replace motor', NULL),
  ('A120', 'alarm', 'Hot melt not ready', 'Errors A121, A122, A123, A124, A127', 'Fix all hot melt errors', NULL),
  ('A121', 'alarm', 'Hot melt error', NULL, NULL, NULL),
  ('A122', 'alarm', 'Hot melt valve open (at start MC)', NULL, NULL, NULL),
  ('A123', 'alarm', 'Hot melt pump not activated', 'Compressed air valve on hot melt closed', 'Open the compressed air valve on the hot melt', NULL),
  ('A124', 'alarm', 'Hot melt low temperature', 'Hot melt has not reached operating temperature', 'Wait until hot melt is hot enough', NULL),
  ('A125', 'alarm', 'Glue wheel is down (at start MC)', '<=', 'Move the glue wheel up using the button', NULL),
  ('A126', 'alarm', 'Glue wheel is up (during idle run at start MC)', '<=', 'Lower the glue wheel using the button', NULL),
  ('A127', 'alarm', 'No connection to hot melt device', E'a) Hot melt is switched off\nb) Connection to hot melt interrupted\nc) Hot melt has no power supply', E'a) Switch on the hot melt (switch, front right bottom)\nb) Check the LAN cable:\n- at the switch in the control cabinet\n- Interface at the bottom, in the control cabinet\n- Interface at the bottom, outside the control cabinet\n- Hot melt connector in front of the magazine', NULL),
  ('A171', 'alarm', 'Thermo suction dosing device', E'a) Circuit breaker =04-1Q0 triggered\nb) Motor defective', E'a) Switch circuit breaker =04-1Q0 on circuit breaker =04-1Q0 Set current limit to 5.0A\nb) Replace motor', NULL),
  ('A172', 'alarm', 'Internal wadding tear', E'a) Cotton wool torn off\nb) Cotton wool not fed through noise sensor\nc) Insufficient friction on noise sensor\nd) Noise sensor sensitivity too low', E'a) Reinsert cotton wool\nb) Pass cotton wool over noise sensor\nc) Adjust the position of the noise sensor forward\nd) Increase sensitivity using a screwdriver', NULL),
  ('A173', 'alarm', 'Cotton tear outside', E'a) Cotton wool torn off\nb) Cotton wool not fed through noise sensor\nc) Insufficient friction on noise sensor\nd) Noise sensor sensitivity too low', E'a) Reinsert cotton wool\nb) Pass cotton wool over noise sensor\nc) Adjust the position of the noise sensor forward\nd) Increase sensitivity using a screwdriver', NULL),
  ('A174', 'alarm', 'Cotton wool dosing not at top (at start MC, when cotton wool feed is off)', 'Wadding dispenser at the bottom', 'Start up the wadding dispenser using the button', NULL),
  ('A176', 'alarm', 'Cotton wool is finished (track 1)', 'Cotton wool on lane 1 empty', 'Refill cotton wool', NULL),
  ('A177', 'alarm', 'Cotton wool finished (track 2)', 'Cotton wool on lane 2 empty', 'Refill cotton wool', NULL),
  ('A179', 'alarm', 'Metering device not at bottom (at start MC)', 'Dossier device is at the top of the MC at start-up', 'Lower the dosing device using the button', NULL),
  ('A180', 'alarm', 'End position of dosing device', 'Dossier machine has not reached end position', E'1) Align sensor\n2) Replace compressed air hoses', NULL),
  ('A185', 'alarm', 'Roll form holder not down (at start MC)', 'Roll form holder cylinder not extended', 'Lower roll form holder using button', NULL),
  ('A190', 'alarm', 'Too many swabs ejected by quality control', E'Too many rods identified as defective by QA in a short period of time:\na) Head shape unsuitable (too small/too large)\nb) Wrong job selected\nc) Contamination at the end of the shaper bar\nd) Contamination on the camera lens\ne) Incorrect trigger timing\nf) Water tear', E'1) Check if there is a cotton tear\n2) Check if camera lens needs cleaning\n3) Check if there is cotton jam (lift doser unit & clean)\n4) Check shaper bar & clean if necessary\n5) Check if there is a jam in stick magazine\n6) Check if there are fuzzy tips: Check for air bubbles in water tubes', E'1) Check the trigger timing of camera\n2) Check camera alignment\n3) Check sensor for "No sticks on chain" (sensor could be misaligned)\n4) Check if the correct job is selected in the camera settings'),
  ('A221', 'alarm', 'Thermo fan drying system', 'circuit breaker =07-2Q2 triggered', E'1) Switch on circuit breaker =07-2Q2\n2) Set circuit breaker =07-2Q2 current limit to 4.4A', NULL),
  ('A222', 'alarm', 'Thermo heating drying system', 'circuit breaker =07-1Q1.1 triggered', E'1) Switch on circuit breaker =07-1Q1.1\n2) Set circuit breaker =07-1Q1.1 current limit to 18.5A', NULL),
  ('A223', 'alarm', 'Thermo suction drying system', 'circuit breaker =07-3Q2 triggered', E'1) Switch on circuit breaker =07-3Q2\n2) circuit breaker =07-3Q2 Set current limit to 4.4A', NULL),
  ('A226', 'alarm', 'Comm. Profinet to FU drying unit fan', 'New frequency converter installed', E'1) Acknowledge error on frequency converter\n2) Restart machine', NULL),
  ('A227', 'alarm', 'Comm. Profinet to FU drying unit suction unit', 'New frequency converter installed', E'1) Acknowledge error on frequency converter\n2) Restart machine', NULL),
  ('A228', 'alarm', 'Error FU drying unit fan', 'New frequency converter installed', E'1) Acknowledge error on frequency converter\n2) Restart machine', NULL),
  ('A229', 'alarm', 'Error FU drying unit suction unit', 'New frequency converter installed', E'1) Acknowledge error on frequency converter\n2) Restart machine', NULL),
  ('A230', 'alarm', 'Error dryer not ready (at MC start)', 'New frequency converter installed', E'1) Acknowledge error on frequency converter\n2) Restart machine', NULL),
  ('A233', 'alarm', 'New - Control restart required (switch off and on)', E'a) Option added in configuration\nb) Option deselected in configuration', 'Main switch: Off -> On', NULL),
  ('A236', 'alarm', 'Max. temperature drying system', 'Max. temp. exceeded -> Jumo has triggered', E'1) Switch on ventilation drying system\n2) Set fans in drying system to run faster\n3) Lower the target temperature\n4) Perform a mechanical reset on the Jumo', NULL),
  ('A239', 'alarm', 'Dryer thermo fan', 'circuit breaker =07-2Q2 triggered', E'1) Switch on circuit breaker =07-2Q2\n2) circuit breaker =07-2Q2 current limiter to 4.4A', NULL),
  ('A243', 'alarm', 'Dryer not switched on at machine start', '<=', 'Start dryer', NULL),
  ('A244', 'alarm', 'Spring tension too low', E'a) Jam in dryer\nb) Belt tension too low\nc) Spring broken', E'a) Remove jam, rebalance dryer\nb) Tighten the belt tensioner\nc) Replace broken spring', NULL),
  ('A245', 'alarm', 'Spring tension too high', E'a) Jam in dryer\nb) Belt tension too low\nc) Spring broken', E'a) Remove jam, rebalance dryer\nb) Tighten the belt tensioner\nc) Replace broken spring', NULL),
  ('A246', 'alarm', 'Dryer outlet temperature outside range', 'Temperature is not within the range', NULL, NULL),
  ('A271', 'alarm', 'Thermo vacuum motor comb', 'Circuit breaker =08-1Q0 triggered', E'1) Switch on circuit breaker =08-1Q0\n2) circuit breaker =08-1Q0 Set current limit to 2.5A', NULL),
  ('A274', 'alarm', 'Too many missing sticks on comb', E'Could not pick up enough sticks with comb:\na) Crossed sticks\nb) Bent sticks\nc) Too many sticks ejected by QS', E'a) Check all transfers (magazine, waterfall)\nb) Check all guides (no jamming)\nc) Reduce QS settings "Max. bad rods in 5s" value', NULL),
  ('A275', 'alarm', 'Too many missing rods in box 1', E'a) Too many individual sticks ejected\nb) Pick-up error\nc) Limit for "Max. missing sticks per pack alarm" set too low', E'a) Adjust magazine including transfer, roll form, waterfall\nb) Adjust pick-up\nc) Increase limit for "Max. missing sticks per package alarm"', NULL),
  ('A276', 'alarm', 'Too many missing rods in box 2', E'a) Too many individual sticks ejected\nb) Pick-up error\nc) Limit for "Max. missing sticks per pack alarm" set too low', E'a) Adjust magazine including transfer, roll form, waterfall\nb) Adjust pick-up\nc) Increase limit for "Max. missing sticks per package alarm"', NULL),
  ('A278', 'alarm', 'Scraper end position error', E'a) Sensor not positioned correctly\nb) Scraper manually moved down', E'a) Correct sensor position\nb) Move scraper up using button', NULL),
  ('A280', 'alarm', 'Scraper not at top (at start MC)', E'a) Sensor not positioned correctly\nb) Scraper manually moved down', E'a) Correct sensor position\nb) Move scraper up using button', NULL),
  ('A281', 'alarm', 'Comb not at top (at start MC)', E'a) Sensor not positioned correctly\nb) Scraper manually moved down', E'a) Correct sensor position\nb) Move scraper up using button', NULL),
  ('A282', 'alarm', 'Comb at bottom in rod counter position', NULL, NULL, NULL),
  ('A321', 'alarm', 'Thermo rotary table', 'circuit breaker =09-1Q2 triggered', E'1) Switch on circuit breaker =09-1Q2\n2) Set circuit breaker =09-1Q2 current limit to 3.0A', NULL),
  ('A322', 'alarm', 'Error FU rotary table', 'New frequency converter installed', E'1) Acknowledge error on frequency converter\n2) Restart machine', NULL),
  ('A323', 'alarm', 'Error rotary table (FU or sensor)', NULL, NULL, NULL),
  ('A324', 'alarm', 'Rotary table not in position', NULL, NULL, NULL),
  ('A327', 'alarm', 'Packaging not ready', 'Error on the packaging system', 'See error on the HMI of the packaging system', NULL),
  ('A328', 'alarm', 'Packaging timeout', 'Error on the packaging system', 'See error on the HMI of the packaging system', NULL),
  ('A329', 'alarm', 'No release of rotary table from packaging', 'Approval from the packaging system not received or received too late', 'See error on the HMI of the packaging system', NULL),
  ('A331', 'alarm', 'No release scraper from BV-2A (timeout)', 'Approval from the packaging system not received or received too late', 'See error on the HMI of the packaging system', NULL),
  ('A332', 'alarm', 'No release scraper from BL12 (timeout)', 'Approval from the packaging system not received or received too late', 'See error on the HMI of the packaging system', NULL),
  ('A340', 'alarm', 'Packaging connector not plugged in', '<=', E'1) Connect plug X10 from packaging system\n2) Insert jumper plug on X10', NULL),
  ('A480', 'alarm', 'Belt tension too high (technician reset)', E'Sensor at top of belt tension cylinder triggered\n- see A245', E'First resolve A245\nthen perform technician reset', NULL),
  ('A481', 'alarm', 'Belt tension too low (technician reset)', E'Sensor at bottom of belt tension cylinder triggered\n- See A244', E'First resolve A244\nThen perform a technician reset', NULL),
  ('W001', 'warning', 'External magazine empty', 'No sticks in outer magazine', 'Refill sticks', NULL),
  ('W002', 'warning', 'Internal magazine empty', 'No sticks in the inner magazine', 'Refill sticks', NULL),
  ('W010', 'warning', 'Min. temperature of external upper rod heater', 'Temperature not yet reached on the outside top', 'Allow to heat up', NULL),
  ('W011', 'warning', 'Min. temperature of rod heater, outside bottom', 'Temperature not yet reached outside bottom', 'Allow to heat up', NULL),
  ('W012', 'warning', 'Min. temperature of rod heater inside top', 'Temperature not yet reached inside top', 'Allow to heat up', NULL),
  ('W013', 'warning', 'Min. temperature of internal bottom rod heater', 'Temperature not yet reached inside bottom', 'Allow to heat up', NULL),
  ('W014', 'warning', 'Warning: Chain tension high', 'Chain tightly tensioned', 'Must be changed soon', NULL),
  ('W015', 'warning', 'Wattage usage even though dosing device is up', '<=', 'Move the dosing device down using the button', NULL),
  ('W020', 'warning', 'Min. temperature drying system not reached', 'Temperature not yet reached', 'Allow to heat up', NULL),
  ('W021', 'warning', 'Conditions for drying system not met', NULL, NULL, NULL),
  ('W022', 'warning', 'Close drying system flap', NULL, NULL, NULL),
  ('W023', 'warning', 'Adjust drying system flap', NULL, NULL, NULL),
  ('W040', 'warning', 'Scraper or rotary table too slow', NULL, NULL, NULL)
ON CONFLICT (code) DO UPDATE SET
  severity                   = EXCLUDED.severity,
  description                = EXCLUDED.description,
  cause                      = EXCLUDED.cause,
  operator_guidance          = EXCLUDED.operator_guidance,
  technical_support_guidance = EXCLUDED.technical_support_guidance;
